### ISSUE TITLE
Перевірити інформацію

### ISSUE THREAD

**Issue by serhiy-yefimov** [serhiy-yefimov/homepage#11]
Потрібно перевірити усю інформацію, підготовлену на попередніх етапах:

- [x] контакти; #8 @serhiy-yefimov 
- [x] таймлайни; #9 @serhiy-yefimov 
- [x] блоки додаткової інформації #10 @serhiy-yefimov

**Comment by serhiy-yefimov** [comment]
- [x] Подумати над формою подачі інформації. #10

**Comment by serhiy-yefimov** [comment]
Зроблено!
